name: API Availability Monitor

on:
  push:
  workflow_dispatch: # Allows you to test it manually

jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check Chicago Data Portal API
        run: |
          # curl -I gets just the headers
          # --fail makes the command exit with an error if the status is 4xx or 5xx
          curl --silent --show-error --fail -I "https://data.cityofchicago.org/resource/ijzp-q8t2.json"
